[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = []
packages = [
    { include = "core", from = "backend" },
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
greet = 'core:cli'
